language: c++

before_install:
- if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
- sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -y qt55* ; source /opt/qt55/bin/qt55-env.sh ; export QTHOME=/opt/qt55 ; fi

script:
 - qmake --version
 - qmake SSBM.pro
 - make
 
deploy:
 - provider: releases
 - api_key: "3940cc517916c31fdbb67f58706eab439f4aecd6"
 - file: SnipeStudio_Budjet_manager/ssbm
 - skip_cleanup: true
 - on:    
    repo: SnipeStudio/SnipeStudio_Budjet_manager
    tags: true
    all_branches: true
# - qmake -project
# - qmake SSBM.pro
# - make
